server.port=8081
spring.application.name=roulette-service

spring.datasource.url=jdbc:postgresql://localhost:5432/roulette
spring.datasource.username=roulette
spring.datasource.password=roulette
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

springdoc.swagger-ui.path=/swagger-ui
