spring.application.name=slotmachine-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/slotmachine_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:slotmachine}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:passwort}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=8082

banking.service.url=${BANKING_SERVICE_URL:http://localhost:8080}

logging.level.org.hibernate.SQL=DEBUG