spring.application.name=casino

#URL zum Banking-Service
casino.banking.url=http://localhost:8080/casino/bank/api/transaction/user/

spring.datasource.url=jdbc:postgresql://localhost:5433/slotmachine_db
spring.datasource.username=slotmachine
spring.datasource.password=passwort
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=8082

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE