spring.application.name=roulette-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/roulette_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:roulette}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:passwort}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=8081

banking.service.url=${BANKING_SERVICE_URL:http://banking-app:8080/casino/bank/api/}

logging.level.org.hibernate.SQL=DEBUG