spring.application.name=banking-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/banking_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:banking}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:passwort}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=8080
#server.servlet.context-path=/casino/bank
banking.service.url=${BANKING_SERVICE_URL:http://banking-app:8080/casino/bank/api/}

logging.level.org.hibernate.SQL=DEBUG
